/*******************************************************************************
 * The MIT License (MIT)
 *
 * Convection calculator app
 * Copyright (C) 2017 Luis F. Cardona S.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package co.edu.itm.www.convectioncalculator;

public class ConfigurationItem {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ConfigurationItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConfigurationItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoolPropJNI.delete_ConfigurationItem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ConfigurationItem(configuration_keys key, boolean val) {
    this(CoolPropJNI.new_ConfigurationItem__SWIG_0(key.swigValue(), val), true);
  }

  public ConfigurationItem(configuration_keys key, int val) {
    this(CoolPropJNI.new_ConfigurationItem__SWIG_1(key.swigValue(), val), true);
  }

  public ConfigurationItem(configuration_keys key, double val) {
    this(CoolPropJNI.new_ConfigurationItem__SWIG_2(key.swigValue(), val), true);
  }

  public ConfigurationItem(configuration_keys key, String val) {
    this(CoolPropJNI.new_ConfigurationItem__SWIG_3(key.swigValue(), val), true);
  }

  public void set_bool(boolean val) {
    CoolPropJNI.ConfigurationItem_set_bool(swigCPtr, this, val);
  }

  public void set_integer(int val) {
    CoolPropJNI.ConfigurationItem_set_integer(swigCPtr, this, val);
  }

  public void set_double(double val) {
    CoolPropJNI.ConfigurationItem_set_double(swigCPtr, this, val);
  }

  public void set_string(String val) {
    CoolPropJNI.ConfigurationItem_set_string(swigCPtr, this, val);
  }

  public configuration_keys get_key() {
    return configuration_keys.swigToEnum(CoolPropJNI.ConfigurationItem_get_key(swigCPtr, this));
  }

}
