/*******************************************************************************
 * The MIT License (MIT)
 *
 * Convection calculator app
 * Copyright (C) 2017 Luis F. Cardona S.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package co.edu.itm.www.convectioncalculator;

public class SpinodalData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SpinodalData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SpinodalData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CoolPropJNI.delete_SpinodalData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTau(DoubleVector value) {
    CoolPropJNI.SpinodalData_tau_set(swigCPtr, this, DoubleVector.getCPtr(value), value);
  }

  public DoubleVector getTau() {
    long cPtr = CoolPropJNI.SpinodalData_tau_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DoubleVector(cPtr, false);
  }

  public void setDelta(DoubleVector value) {
    CoolPropJNI.SpinodalData_delta_set(swigCPtr, this, DoubleVector.getCPtr(value), value);
  }

  public DoubleVector getDelta() {
    long cPtr = CoolPropJNI.SpinodalData_delta_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DoubleVector(cPtr, false);
  }

  public void setM1(DoubleVector value) {
    CoolPropJNI.SpinodalData_M1_set(swigCPtr, this, DoubleVector.getCPtr(value), value);
  }

  public DoubleVector getM1() {
    long cPtr = CoolPropJNI.SpinodalData_M1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DoubleVector(cPtr, false);
  }

  public SpinodalData() {
    this(CoolPropJNI.new_SpinodalData(), true);
  }

}
